function dirPath = getAuditoryStimsAnalysisDirPath(animal,animalSession)
    dirPath = [SdLocalPcDef.ANALYSIS_DIR filesep ...
        DirPathsFromBaseDir.AUDITORY_STIM_DIR_NAME filesep ...
        sprintf('%s - %d',animal,animalSession)];
end