function emgTraceDirPath = getEmgTraceDirPath(sessionInfo)
    emgTraceDirPath = [SdLocalPcDef.ANALYSIS_DIR filesep ...
        DirPathsFromBaseDir.EMG_ANALYSIS_DIR_NAME filesep ...
        DirPathsFromBaseDir.TRACES_DIR_NAME  filesep ...
        getSessionDirName(sessionInfo)];
end