function muaTraceDirPath = getMuaTraceDirPath(animal,animalSession)
    muaTraceDirPath = [SdLocalPcDef.ANALYSIS_DIR filesep ...
        DirPathsFromBaseDir.MUA_ANALYSIS_DIR_NAME filesep ...
        DirPathsFromBaseDir.TRACES_DIR_NAME  filesep ...
        sprintf('%s - %d',animal,animalSession)];
end