function rawMatDirPath = getRawTraceMatDirPath(animal,animalSession)
    rawMatDirPath = [SdLocalPcDef.TEMP_ANALYSIS_DIR filesep ...
        DirPathsFromBaseDir.RAW_TRACES_MAT_DIR_NAME filesep ...
        sprintf('%s - %d',animal,animalSession)];
end