function spikesSortingDirPath = getSpikesSortingDirPath(animal,animalSession)
    spikesSortingDirPath = [SdLocalPcDef.ANALYSIS_DIR filesep ...
        DirPathsFromBaseDir.SPIKES_ANALYSIS_DIR_NAME filesep ...
        DirPathsFromBaseDir.SPIKE_SORTING_DIR_NAME filesep ...
        sprintf('%s - %d',animal,animalSession)];
end