function sleepScoringDirPath = getSleepScoringDirPath(sessionInfo)
    sleepScoringDirPath = [SdLocalPcDef.ANALYSIS_DIR filesep ...
        DirPathsFromBaseDir.SLEEP_SCORING_DIR_NAME filesep ...
        getSessionDirName(sessionInfo) ];
end